# Generated by Django 6.0.2 on 2026-02-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_userprofile_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name",
        ),
    ]
