# Generated by Django 5.2.11 on 2026-02-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="penalty_deducted",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAYMENT_PENDING", "Payment Pending"),
                    ("OWNER_PENDING", "Waiting Owner Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("AUTO_CANCELLED", "Auto Cancelled"),
                    ("CANCELLED", "Cancelled by Renter"),
                    ("REFUNDED", "Refunded"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                ],
                default="PAYMENT_PENDING",
                max_length=30,
            ),
        ),
    ]
