# Generated by Django 5.2.11 on 2026-02-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_booking_delivered_at_booking_is_settled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="delivered_at",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="razorpay_signature",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="returned_at",
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAYMENT_PENDING", "Payment Pending"),
                    ("OWNER_PENDING", "Waiting Owner Approval"),
                    ("APPROVED", "Approved"),
                    ("ACTIVE", "Active"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("AUTO_CANCELLED", "Auto Cancelled"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PAYMENT_PENDING",
                max_length=30,
            ),
        ),
    ]
