# Generated by Django 5.2.11 on 2026-03-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_remove_booking_delivered_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAYMENT_PENDING", "Payment Pending"),
                    ("OWNER_PENDING", "Waiting Owner Approval"),
                    ("APPROVED", "Approved"),
                    ("ACTIVE", "Active"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("ADMIN_SETTLEMENT_PENDING", "Admin Settlement Pending"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("AUTO_CANCELLED", "Auto Cancelled"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PAYMENT_PENDING",
                max_length=30,
            ),
        ),
    ]
