# Generated by Django 5.2.11 on 2026-03-10 01:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0009_asset_deposit"),
        ("chat", "0002_message_is_read"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={("asset", "owner", "renter")},
        ),
    ]
