# Generated by Django 5.2.11 on 2026-03-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_message_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
