apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rentease.fullname" . }}-celery-worker
  labels:
    {{- include "rentease.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.celeryWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "rentease.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-worker
  template:
    metadata:
      labels:
        {{- include "rentease.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery-worker
    spec:
      serviceAccountName: {{ default (include "rentease.fullname" .) .Values.serviceAccount.name }}
      containers:
        - name: celery-worker
          image: "{{ .Values.celeryWorker.image.repository }}:{{ .Values.celeryWorker.image.tag }}"
          imagePullPolicy: {{ .Values.celeryWorker.image.pullPolicy }}
          command: {{- toYaml .Values.celeryWorker.command | nindent 12 }}
          args: {{- toYaml .Values.celeryWorker.args | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "rentease.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secrets.existingSecret | default (printf "%s-secret" (include "rentease.fullname" .)) }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.celeryWorker.resources | nindent 12 }}
