apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rentease.fullname" . }}-celery-beat
  labels:
    {{- include "rentease.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.celeryBeat.replicaCount }}
  selector:
    matchLabels:
      {{- include "rentease.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-beat
  template:
    metadata:
      labels:
        {{- include "rentease.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery-beat
    spec:
      serviceAccountName: {{ default (include "rentease.fullname" .) .Values.serviceAccount.name }}
      containers:
        - name: celery-beat
          image: "{{ .Values.celeryBeat.image.repository }}:{{ .Values.celeryBeat.image.tag }}"
          imagePullPolicy: {{ .Values.celeryBeat.image.pullPolicy }}
          command: {{- toYaml .Values.celeryBeat.command | nindent 12 }}
          args: {{- toYaml .Values.celeryBeat.args | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "rentease.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secrets.existingSecret | default (printf "%s-secret" (include "rentease.fullname" .)) }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.celeryBeat.resources | nindent 12 }}
