apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rentease.fullname" . }}-config
  labels:
    {{- include "rentease.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.config.DEBUG | quote }}
  AI_SERVICE_TIMEOUT_SECONDS: {{ .Values.config.AI_SERVICE_TIMEOUT_SECONDS | quote }}
