apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rentease.fullname" . }}-nginx
  labels:
    {{- include "rentease.labels" . | nindent 4 }}
data:
  default.conf: |
    server {

        listen 80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location /api/ {
            proxy_pass http://{{ include "rentease.fullname" . }}-web:{{ .Values.service.web.port }};
        }

{{- if .Values.aiService.enabled }}
        location /ai/ {
            proxy_pass http://{{ include "rentease.fullname" . }}-ai:{{ .Values.service.aiService.port }};
        }
{{- end }}

{{- if .Values.frontend.enabled }}
        location / {
            proxy_pass http://{{ include "rentease.fullname" . }}-frontend:{{ .Values.service.frontend.port }};
        }
{{- else }}
        location / {
            return 404;
        }
{{- end }}

    }
