{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rentease.fullname" . }}-postgres
  labels:
    {{- include "rentease.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "rentease.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "rentease.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.existingSecret | default (printf "%s-secret" (include "rentease.fullname" .)) }}
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rentease.fullname" . }}-postgres
  labels:
    {{- include "rentease.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "rentease.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - port: {{ .Values.postgres.containerPort }}
      targetPort: {{ .Values.postgres.containerPort }}
      protocol: TCP
      name: postgres
{{- end }}
