{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rentease.fullname" . }}-redis
  labels:
    {{- include "rentease.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "rentease.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "rentease.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.containerPort }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rentease.fullname" . }}-redis
  labels:
    {{- include "rentease.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.redis.type }}
  selector:
    {{- include "rentease.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: {{ .Values.service.redis.port }}
      targetPort: {{ .Values.redis.containerPort }}
      protocol: TCP
      name: redis
{{- end }}
