{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rentease.fullname" . }}-secret
  labels:
    {{- include "rentease.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.data.SECRET_KEY | quote }}
  POSTGRES_DB: {{ .Values.secrets.data.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.secrets.data.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.data.POSTGRES_PASSWORD | quote }}
  POSTGRES_HOST: {{ .Values.secrets.data.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.secrets.data.POSTGRES_PORT | quote }}
  CELERY_BROKER_URL: {{ .Values.secrets.data.CELERY_BROKER_URL | quote }}
  REDIS_CACHE_URL: {{ .Values.secrets.data.REDIS_CACHE_URL | quote }}
  AI_SERVICE_URL: {{ .Values.secrets.data.AI_SERVICE_URL | quote }}
  GROQ_API_KEY: {{ .Values.secrets.data.GROQ_API_KEY | quote }}
  GROQ_MODEL: {{ .Values.secrets.data.GROQ_MODEL | quote }}
  GROQ_API_URL: {{ .Values.secrets.data.GROQ_API_URL | quote }}
  AWS_REGION: {{ .Values.secrets.data.AWS_REGION | quote }}
  AWS_STORAGE_BUCKET_NAME: {{ .Values.secrets.data.AWS_STORAGE_BUCKET_NAME | quote }}
  AWS_S3_REGION_NAME: {{ .Values.secrets.data.AWS_S3_REGION_NAME | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.data.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.data.AWS_SECRET_ACCESS_KEY | quote }}
  AWS_S3_FILE_OVERWRITE: {{ .Values.secrets.data.AWS_S3_FILE_OVERWRITE | quote }}
  AWS_QUERYSTRING_AUTH: {{ .Values.secrets.data.AWS_QUERYSTRING_AUTH | quote }}
  NOTIFICATION_QUEUE_URL: {{ .Values.secrets.data.NOTIFICATION_QUEUE_URL | quote }}
  EMAIL_HOST: {{ .Values.secrets.data.EMAIL_HOST | quote }}
  EMAIL_PORT: {{ .Values.secrets.data.EMAIL_PORT | quote }}
  EMAIL_USE_TLS: {{ .Values.secrets.data.EMAIL_USE_TLS | quote }}
  EMAIL_HOST_USER: {{ .Values.secrets.data.EMAIL_HOST_USER | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.secrets.data.EMAIL_HOST_PASSWORD | quote }}
  RAZORPAY_KEY_ID: {{ .Values.secrets.data.RAZORPAY_KEY_ID | quote }}
  RAZORPAY_KEY_SECRET: {{ .Values.secrets.data.RAZORPAY_KEY_SECRET | quote }}
  PLATFORM_COMMISSION: {{ .Values.secrets.data.PLATFORM_COMMISSION | quote }}
  OWNER_APPROVAL_TIMEOUT_HOURS: {{ .Values.secrets.data.OWNER_APPROVAL_TIMEOUT_HOURS | quote }}
{{- end }}
