# Generated by Django 6.0.2 on 2026-02-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_alter_assetavailability_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="asset_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
