# Generated by Django 6.0.2 on 2026-02-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_category_asset_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_image",
            field=models.ImageField(blank=True, null=True, upload_to="asset_image/"),
        ),
    ]
