# Generated by Django 5.2.11 on 2026-02-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_alter_asset_id_alter_assetavailability_id_and_more"),
        (
            "profiles",
            "0006_alter_district_id_alter_panchayat_id_alter_taluk_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.panchayat",
            ),
        ),
    ]
