# Generated by Django 5.2.11 on 2026-02-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_alter_asset_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="deposit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
