# Generated by Django 6.0.2 on 2026-02-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_devicefingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_otp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
