# Generated by Django 5.2.11 on 2026-02-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_penalty_deducted_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_settled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAYMENT_PENDING", "Payment Pending"),
                    ("OWNER_PENDING", "Waiting Owner Approval"),
                    ("APPROVED", "Approved"),
                    ("DELIVERED", "Delivered to Renter"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                    ("AUTO_CANCELLED", "Auto Cancelled"),
                    ("CANCELLED", "Cancelled by Renter"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PAYMENT_PENDING",
                max_length=30,
            ),
        ),
    ]
