# Replace <ACCOUNT> and <REGION> with your AWS details.
# Example:
# repository: "123456789012.dkr.ecr.ap-south-1.amazonaws.com/rentease-app"

imagePullSecrets:
  - name: ecr-secret

web:
  image:
    repository: "677060981954.dkr.ecr.eu-north-1.amazonaws.com/rentease-app"
    tag: "20260401-1"
    pullPolicy: Always
  replicaCount: 1
  command: ["/bin/sh", "-c"]
  args:
    - "python manage.py collectstatic --noinput && gunicorn RentEase.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"

celeryWorker:
  image:
    repository: "677060981954.dkr.ecr.eu-north-1.amazonaws.com/rentease-app"
    tag: "20260401-1"
    pullPolicy: Always
  replicaCount: 1

celeryBeat:
  image:
    repository: "677060981954.dkr.ecr.eu-north-1.amazonaws.com/rentease-app"
    tag: "20260401-1"
    pullPolicy: Always
  replicaCount: 0

aiService:
  enabled: false

frontend:
  enabled: false

redis:
  enabled: true

postgres:
  enabled: true

qdrant:
  enabled: false

service:
  nginx:
    type: NodePort
    port: 80

ingress:
  enabled: false

config:
  DEBUG: "False"

secrets:
  existingSecret: "rentease-secret"
  data: {}

extraEnv:
  - name: STATICFILES_STORAGE
    value: "whitenoise.storage.CompressedStaticFilesStorage"
  - name: CSRF_TRUSTED_ORIGINS
    value: "http://13.62.119.212:30423"
  - name: SERVE_MEDIA
    value: "True"
