# Generated by Django 5.2.11 on 2026-03-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_ownerbankdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
