# Generated by Django 5.2.11 on 2026-03-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_fcm_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="fcm_token",
        ),
    ]
