# Generated by Django 5.2.11 on 2026-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_user_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="trust_score",
            field=models.IntegerField(default=800),
        ),
    ]
