# Generated by Django 5.2.12 on 2026-03-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_assetreview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assetreview',
            new_name='assets_asse_asset_i_75a15c_idx',
            old_name='assets_assetr_asset_i_8a0a67_idx',
        ),
        migrations.RenameIndex(
            model_name='assetreview',
            new_name='assets_asse_reviewe_bd796a_idx',
            old_name='assets_assetr_reviewe_f73429_idx',
        ),
        migrations.AlterField(
            model_name='assetreview',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
