# Generated by Django 6.0.2 on 2026-02-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="id_document",
            field=models.FileField(
                blank=True, null=True, upload_to="verification_docs/"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("NOT_SUBMITTED", "Not Submitted"),
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="NOT_SUBMITTED",
                max_length=20,
            ),
        ),
    ]
