# Generated by Django 6.0.2 on 2026-02-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0002_userprofile_id_document_userprofile_rejection_reason_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
