# Generated by Django 6.0.2 on 2026-02-17 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_remove_userprofile_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Panchayat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="city",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="panchayat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="profiles.panchayat",
            ),
        ),
        migrations.CreateModel(
            name="Taluk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taluks",
                        to="profiles.district",
                    ),
                ),
            ],
            options={
                "unique_together": {("district", "name")},
            },
        ),
        migrations.AddField(
            model_name="panchayat",
            name="taluk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="panchayats",
                to="profiles.taluk",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="panchayat",
            unique_together={("taluk", "name")},
        ),
    ]
